services:
  redis-caching:
    image: redis:latest
    container_name: redis-caching
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

  rabbitmq-broker:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  mssql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    networks:
      - app-network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.0
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - app-network

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi
    container_name: identity-api
    build:
      context: .
      dockerfile: src/Identity/Identity.API/Dockerfile
    ports:
      - 5006:8080
      - 5007:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

  cart-api:
    image: ${DOCKER_REGISTRY-}cartapi
    container_name: cart-api
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile
    ports:
      - 5002:8080
      - 5003:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - redis-caching
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

  ordering-api:
    image: ${DOCKER_REGISTRY-}orderingapi
    container_name: ordering-api
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile
    ports:
      - 5004:8080
      - 5005:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

  payment-processor:
    image: ${DOCKER_REGISTRY-}paymentprocessor
    container_name: payment-processor
    build:
      context: .
      dockerfile: src/Payment/Payment.Processor/Dockerfile
    ports:
      - 5008:8080
      - 5009:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

  api-gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - 7000:8080
      - 7001:8081
    depends_on:
      - identity-api
      - catalog-api
      - cart-api
      - ordering-api
      - payment-processor
    networks:
      - app-network
    environment:
      LOGSTASH_URL: logstash:5044 # Add logstash endpoint for logging

networks:
  app-network:
    driver: bridge
