services:

  redis-caching:
    image: redis:7.4.2-alpine
    container_name: redis-caching
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

  rabbitmq-broker:
    image: rabbitmq:4.0.5-management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.containers/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.containers/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  mssql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433
    volumes:
      - ./.containers/data:/var/opt/mssql/data
      - ./.containers/log:/var/opt/mssql/log
      - ./.containers/secrets:/var/opt/mssql/secrets
    networks:
      - app-network

  # jaegar-agent:
  #   image: jaegertracing/jaeger:2.2.0
  #   container_name: jaegar-agent
  #   ports:
  #     - 4317:4317
  #     - 4318:4318
  #     - 5778:5778
  #     - 9411:9411
  #     - 16686:16686
  #   networks:
  #     - app-network

  seq-logging:
        image: datalust/seq:latest
        container_name: seq-logging
        volumes:
          - ./.containers/seq/data:/data
        environment:
          - ACCEPT_EULA=Y
        networks:
          - app-network
        ports:
          - 5341:5341
          - 8081:80

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi
    container_name: Identity.API
    build:
      context: .
      dockerfile: src/Identity/Identity.API/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq-logging:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5006:8080
      - 5007:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - seq-logging
    networks:
      - app-network

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: Catalog.API
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq-logging:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - seq-logging
    networks:
      - app-network

  cart-api:
    image: ${DOCKER_REGISTRY-}cartapi
    container_name: Cart.API
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq-logging:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5002:8080
      - 5003:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - redis-caching
      - seq-logging
    networks:
      - app-network

  ordering-api:
    image: ${DOCKER_REGISTRY-}orderingapi
    container_name: Ordering.API
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq-logging:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5004:8080
      - 5005:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - seq-logging
    networks:
      - app-network

  payment-processor:
    image: ${DOCKER_REGISTRY-}paymentprocessor
    container_name: Payment.Processor
    build:
      context: .
      dockerfile: src/Payment/Payment.Processor/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq-logging:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5008:8080
      - 5009:8081
    depends_on:
      - mssql-database
      - rabbitmq-broker
      - seq-logging
    networks:
      - app-network

  api-gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: ApiGateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - 7000:8080
      - 7001:8081
    depends_on:
      - identity-api
      - catalog-api
      - cart-api
      - ordering-api
      - payment-processor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
